### ISSUE TITLE
installer.sh loops forever on vcenter question

### ISSUE THREAD

**Issue by CrazySpence** [Altoros/SelfPortal#5]
you have 

 while [[ -z "$vcenter" ]]
        do
                read -p "Enter VMWare vCenter server address (like https://vcenter.example.com): " $vcenter
        done

I think it should be

 while [[ -z "$vcenter" ]]
        do
                read -p "Enter VMWare vCenter server address (like https://vcenter.example.com): " vcenter
        done

Looks like the whole vmware part was done that way

**Comment by ArseniiPetrovich** [comment]
Great thanks!
Released a hotfix patch.
